### ISSUE TITLE
geograpy-ntlk error

### ISSUE THREAD

**Issue by benmaier** [ushahidi/geograpy#13]
This is an issue fork from #4 by @shun-liang. I have the same problem.

>  When trying to run geograpy-nltk, I get the following error:
> 
> Traceback (most recent call last):
>   File "/Users/shun/.virtualenvs/hn_hiring_trend/bin/geograpy-nltk", line 5, in <module>
>     nltk.downloader('maxent_ne_chunker')
> TypeError: 'module' object is not callable

**Comment by benmaier** [comment]
Already fixed in open pull requests.

**Comment by nickpolet** [comment]
I still get this error when installing from pip. Is there an easy way to fix this?

**Comment by NikolayBlokhin** [comment]
@nickpolet it's helped me: https://github.com/ushahidi/geograpy/pull/1/files
